# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-22 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_feeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
